# site settings
title: LostThoughtStudios
subtitle:
email: rahult5@live.in
description: About Our Group
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Lehrter Straße 
city:
state:  Berlin
zip_code: 10557
country: Germany
phone: (XXX) XXX-XXXX

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: #www.facebook.com
github_url: https://github.com/Arjun-5
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/lostthoughtstudios/
linkedin_url: https://www.linkedin.com/in/rahult5/
pinterest_url:
slack_url: #www.slack.com
twitter_url: #www.twitter.com
youtube_url: #https://www.youtube.com
globe_url:  https://www.arjunportfolio5.wordpress.com

# build settings
markdown: kramdown

sass:
  style: compressed
